import {createContext} from "react";

export const SchoolContext = createContext({
    filterActive: null,
    filterRegion: null,
    filterSchoolType: null,
    getSchools: () => {},
    handleChangeFilterActive:(active) => {},
    handleChangeFilterSchoolType:(schoolType) => {},
    handleChangeFilterRegion:(region) => {},
    handleChangeNewSchoolEdrpou: (edrpou) => {},
    handleChangeNewSchoolName: (name) => {},
    handleChangeNewSchoolRegion: (region) => {},
    handleChangeNewSchoolSchoolType: (schoolType) => {},
    handleClickCreationDialogClose: () => {},
    handleClickCreationDialogConfirm: () => {},
    handleClickCreationDialogOpen: () => {},
    handleClickDeactivationDialogClose: () => {},
    handleClickDeactivationDialogConfirm: () => {},
    handleClickDeactivationDialogOpen: (id, name) => {},
    handleClickFilter: (id, name) => {},
    isOpenCreationDialog: false,
    isOpenDeactivationDialog: false,
    nameDeactivationDialog: null,
    newSchoolEdrpou: null,
    newSchoolName: null,
    newSchoolRegion: null,
    newSchoolSchoolType: null,
    schools:[],
})
