import {createContext} from "react";

export const SchoolContext = createContext({
    edrpouNewSchool: null,
    filterActive: null,
    filterRegion: null,
    filterSchoolType: null,
    getSchools: () => {},
    handleChangeEdrpouNewSchool: (edrpou) => {},
    handleChangeFilterActive:(active) => {},
    handleChangeFilterSchoolType:(schoolType) => {},
    handleChangeFilterRegion:(region) => {},
    handleChangeNameNewSchool: (name) => {},
    handleChangeRegionNewSchool: (region) => {},
    handleChangeSchoolTypeNewSchool: (schoolType) => {},
    handleClickCreationDialogClose: () => {},
    handleClickCreationDialogConfirm: () => {},
    handleClickCreationDialogOpen: () => {},
    handleClickDeactivationDialogClose: () => {},
    handleClickDeactivationDialogConfirm: () => {},
    handleClickDeactivationDialogOpen: (id, name) => {},
    handleClickFilter: (id, name) => {},
    isOpenCreationDialog: false,
    isOpenDeactivationDialog: false,
    nameDeactivationDialog: null,
    nameNewSchool: null,
    regionNewSchool: null,
    schoolTypeNewSchool: null,
    schools:[],
})
